fix(bootstrapper): Check module function configure before execute it
aurelia/bootstrapper pull request #46
Opened 2016-08-14 00:41 UTC by pnizer

Prevent error 'TypeError: customConfig.configure it not a function' when a module is set by <... aurelia-app="my-module"> and my-module.js does not have exported a configure function.

2016-08-26 00:54 UTC, EisenbergEffect commented
Can you describe how you are using this without the configure function? I'd like to understand your use case and approach before merging. Thanks!

2016-08-30 17:18 UTC, pnizer commented
The application does not work without the configure function, but the error in console does not help someone to understand that the error is the absence of configure function. Maybe the real 'solution' is throwing an exception with a message explaining the problem to developer.

2016-09-16 15:55 UTC, EisenbergEffect commented on src/index.js
> +    return loader.loadModule(configModuleId).then(customConfig => customConfig.configure && customConfig.configure(aurelia));
I definitely think that throwing a descriptive error if the `configure` method is missing would be better than failing silently. Would you be willing to update this PR with that change?

2016-10-04 05:16 UTC, EisenbergEffect requested changes
Can we throw an error instead of failing silently?

2016-10-04 17:11 UTC, pnizer commented
Throwing a descriptive error when there is no configure function.

2016-10-13 05:20 UTC, EisenbergEffect approved these changes

2016-10-13 05:20 UTC, merged