chore(build): document dynamic dependencies
aurelia/bootstrapper pull request #57
Opened 2017-01-18 18:58 UTC by jods4

Add `PLATFORM.moduleName()` around `aurelia-framework`.

See aurelia/pal#21

2017-01-30 23:52 UTC, jods4 commented
@niieani I added the changes you needed for the starting Promise on top of my previous PR.

2017-01-31 09:21 UTC, niieani commented on src/index.js
> +    .then(([frameworkName,]) => loader.loadModule(frameworkName))
Trailing `,` here

2017-01-31 09:29 UTC, niieani approved these changes

2017-01-31 09:30 UTC, niieani requested changes
The changes look good, but we should probably test this on different platforms before we release to ensure we didn't introduce any bugs.

TODO: One more thing we should add is expose the startingPromise under `PLATFORM.global` so that plugins can hook it without having access to the loader/module interface. 

@EisenbergEffect can you take a look at the second commit (fix). This is required to fix a race condition in protractor-plugin as it pretty much enables to programatically ensure Aurelia is fully loaded before any action that expects it is attempted.

2017-01-31 10:10 UTC, jods4 commented on src/index.js
> +    .then(([frameworkName,]) => loader.loadModule(frameworkName))
Yes, I like it as it shows there is more in the array but I'm ignoring it.
I can remove it, the code would compile and work the same.

I also like trailing commas in arrays and objects (like line 121) as it's easier to add/remove items and it makes clean diffs (only the added/removed line is touched).

2017-01-31 10:21 UTC, jods4 commented
> TODO: One more thing we should add is expose the startingPromise under  PLATFORM.global  so that plugins can hook it without having access to the loader/module interface.

I'm not sure I understand.
Plugins `configure()` run during startup. Your use case would be a plugin that wants to do something after its application has completly started?
They can already use `Aurelia.start()` for that.
**Note that this method has a bug as well:** the promise returned when called a second time (e.g. from your plugin) resolves too early. I plan to submit a PR for that as well.

`starting` is also easy to consume globally anyway: `import { starting } from "aurelia-bootstrapper"`. (except if you're the first to do that you launch the startup process...)

`PLATFORM.global` doesn't seem a good location to put anything. It's `window`, i.e. global namespace pollution and can be overwritten by anything.

2017-01-31 15:13 UTC, niieani commented
Sorry, I meant external "plugins", like the ones for testing (e.g. protractor), not Aurelia plugins. Yes, I'm aware global is the same as `window`. The idea is that an external module has to be able to access that Promise. If it's not aware of the module loader (and we do not want it to be), the Promise has to be exposed somewhere where it would be accessible globally. Therefore it is not possible to consume it with `import { starting } from "aurelia-bootstrapper"` outside of the bundler context (e.g. from the debugger console in the browser).

2017-01-31 17:50 UTC, stoffeastrom commented
I might remember wrong but I think theres an `event` fired when it should be composed?

2017-01-31 18:37 UTC, jods4 commented
@stoffeastrom 
> I might remember wrong but I think theres an event fired when it should be composed?

There is one, although I don't think it indicates which app has loaded, so is a bit harder to use in a general context if you want to support more than one Aurelia app starting up in the same window.
More than one app is not a common scenario, though.

@niieani I still don't feel good about polluting the global scope. You could hold the same argument for everything: "I would like to have access to the Aurelia app/the loader/the DI".
If you need to debug from the browser console, you can use `webpack.NamedModulesPlugin` and all modules will have friendly names, which should enable you to easily request "aurelia-bootstrapper" from the console.

2017-01-31 18:53 UTC, niieani commented
@jods4 it's not about debugging. It's about having programmatic information that the app has bootstrapped. I don't think it's the same as having access to app/loader/DI in the global context, because you only use those from within the app. This is a different case. We want to be able to know that Aurelia is ready, without having to fallback to any hacks. 

> you can use `webpack.NamedModulesPlugin` (...)

No, that would make this a webpack-specific solution, possible only with a specific set of plugins. Not portable, not good, IMO.

I wouldn't feel comfortable with running different code for e2e tests, as e2e tests are supposed to run on the same code as is being run in production. If we don't want to expose anything globally, another solution might be to emit a custom event on `window`, signalling that the Aurelia app has bootstrapped. Ultimately, the end-goal is the same, and the use similar (global event vs global variable).

@EisenbergEffect thoughts on the best solution?

2017-01-31 19:13 UTC, jods4 commented
@niieani  like `aurelia-started`? 
https://github.com/aurelia/framework/blob/master/src/aurelia.js#L89

2017-01-31 19:36 UTC, niieani commented
@jods4 sure, I was pretty sure we had something like this. I wonder why we don't use it in the protractor plugin (I'm not the original author, I've only moved the files from `aurelia-tools` where it was located previously). Is that event used anywhere, or is it more like public API for external tool use?

2017-02-05 00:06 UTC, EisenbergEffect commented
It was originally used in the protractor plugin, I think.

2017-02-05 00:06 UTC, merged

2017-02-05 00:06 UTC, EisenbergEffect commented
Good job everyone! I think this version is much cleaner than the previous.

2017-02-05 16:47 UTC, niieani commented on src/index.js
> +    .then(([frameworkName,]) => loader.loadModule(frameworkName))
@jods4 Ok, that's cool. I like trailing commas in arrays and objects, just never saw/used it in combination with destructuring. Good use case.

2017-02-05 16:55 UTC, niieani commented
@jods4 the problem with the [event](https://github.com/aurelia/framework/blob/d650b01993aa2db81f8c9587793b73b2d1f0476d/src/aurelia.js#L176) is that it happens once, and if we happen to start listening for the event _too late_, we have no way of knowing whether Aurelia has started or not. This is my working theory on why protractor-plugin has stopped working without a reason, i.e. the new stack is so fast, that the plugin starts listening to the event too late, when Aurelia is already composed, and hence no e2e tests ever get run. A global would make it possible to know if Aurelia is ready, without external tooling having to race Aurelia with its loading time, just to be able to catch one of those `aurelia-started` or `aurelia-composed` events. 

An alternative to a global would be an attribute on the body/component that is being managed by Aurelia, like `<body aurelia-started aurelia-composed>`. We could then simply check if any elements contain `[aurelia-composed]` attribute, and run the rest of the code synchronously or asynchronously after waiting for the callback from the event. 

Unless there's a better way, I'm all ears.

2017-02-05 17:19 UTC, jods4 commented
@niieani Talk to me in the chat, because I'm not familiar with how the protractor plugin works.

2017-02-05 18:18 UTC, niieani commented
https://github.com/aurelia/protractor-plugin/pull/4 seems to have fixed the race condition, however I still feel some other indication of a successful start/composition would be a good improvement.

2017-02-05 19:13 UTC, jods4 commented
@niieani That fix seems very hacky. Why don't you do the same thing as for the router?
https://github.com/aurelia/protractor-plugin/blob/2802216a0e82e8f0b873f1a9e2114b57ea875ca9/index.js#L39

If `[aurelia-app]` has an `aurelia` property you can do `.aurelia.start(...)`.
If it doesn't then it has not loaded yet and you can wait for the event.

2017-02-05 19:36 UTC, niieani commented
@jods4 Indeed, it could. I'll try that idea. In fact, this is not my code, I just separated it into it's own repo, so I haven't gone deep enough.